#!/usr/bin/env python3
import os

from src.args import arg_handler, get_args
from src.utils import seconds_to_formated_hours
from src.worklogs import get_worklogs_by_interval, get_worklogs_sum
from src.yaml_parser import yaml_load

config = yaml_load(os.path.join(os.path.dirname(__file__), "config.yaml"))

from_date, to_date = get_args(arg_handler())

acc = 0
for jira, data in config.items():
    print(f"Jira: {jira.upper()}")
    worklogs = get_worklogs_by_interval(data, from_date, to_date)
    time = get_worklogs_sum(worklogs)
    acc += time
    print(f"Time sum: {time/3600} Hours\n")

print(f"Total time: {acc/3600} Hours")
print(f"Total formated time: {seconds_to_formated_hours(acc)}")
